export const test_bollards_list = [
   {
      "b_letter":"",
      "b_name":"",
      "b_number":36,
      "id":39,
      "image_icon":"6b6f318eb9701310.jpg"
   },
   {
      "b_letter":"",
      "b_name":"",
      "b_number":33,
      "id":36,
      "image_icon":"84bcd953b6cb9785.jpg"
   },
   {
      "b_letter":"",
      "b_name":"",
      "b_number":28,
      "id":31,
      "image_icon":"91daf6e9e0dc99fd.jpg"
   },
   {
      "b_letter":"",
      "b_name":"",
      "b_number":27,
      "id":30,
      "image_icon":"1b5e007272220edb.jpg"
   },
   {
      "b_letter":"",
      "b_name":"Coin de la Beuffarde",
      "b_number":11,
      "id":15,
      "image_icon":"d9093d663fb67db6.jpg"
   },
   {
      "b_letter":"",
      "b_name":"Beuffarde",
      "b_number":10,
      "id":11,
      "image_icon":"b673f71ca97afdcf.jpg"
   },
   {
      "b_letter":"",
      "b_name":"",
      "b_number":7,
      "id":8,
      "image_icon":"b9c559e2cdd6e8d3.jpg"
   },
   {
      "b_letter":"",
      "b_name":"",
      "b_number":51,
      "id":54,
      "image_icon":"90ed7af297c625fb.jpg"
   }
];

export const test_bollards_list_filtered = [[
    {
       "b_letter":"",
       "b_name":"",
       "b_number":36,
       "id":39,
       "image_icon":"6b6f318eb9701310.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":33,
       "id":36,
       "image_icon":"84bcd953b6cb9785.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":28,
       "id":31,
       "image_icon":"91daf6e9e0dc99fd.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":27,
       "id":30,
       "image_icon":"1b5e007272220edb.jpg"
    },
    {
       "b_letter":"",
       "b_name":"Coin de la Beuffarde",
       "b_number":11,
       "id":15,
       "image_icon":"d9093d663fb67db6.jpg"
    },
    {
       "b_letter":"",
       "b_name":"Beuffarde",
       "b_number":10,
       "id":11,
       "image_icon":"b673f71ca97afdcf.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":7,
       "id":8,
       "image_icon":"b9c559e2cdd6e8d3.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":51,
       "id":54,
       "image_icon":"90ed7af297c625fb.jpg"
    }
],
[
    {
       "b_letter":"",
       "b_name":"",
       "b_number":2,
       "id":3,
       "image_icon":"e29b594d3a24e099.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":3,
       "id":4,
       "image_icon":"4b635e63a0cadfe8.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":4,
       "id":5,
       "image_icon":"7912ec4e83a3052d.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":5,
       "id":6,
       "image_icon":"a9665f2a2e842c63.jpg"
    },
    {
       "b_letter":"",
       "b_name":"Vitiau",
       "b_number":1,
       "id":2,
       "image_icon":"826c55aebf4647dc.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":52,
       "id":55,
       "image_icon":"ee23677ee816de42.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":9,
       "id":10,
       "image_icon":"447a750ec8444c4e.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":53,
       "id":56,
       "image_icon":"4a7009e8ef06e824.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":12,
       "id":16,
       "image_icon":"8ff823e0456788f7.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":14,
       "id":18,
       "image_icon":"d23aa027ba4470d5.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":17,
       "id":21,
       "image_icon":"03613de1d21e6547.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":18,
       "id":22,
       "image_icon":"f20a51c0eee81314.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":19,
       "id":23,
       "image_icon":"6a49d02b089a1fcd.jpg"
    },
    {
       "b_letter":"",
       "b_name":"",
       "b_number":20,
       "id":24,
       "image_icon":"a17cab4f257a4a5e.jpg"
    }
 ]]